---
title: "Tabela FII"
author: "Eduardo Ben-Hur"
date: "2023-03-02"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Carrega as bibliotecas necessárias
library(flexdashboard)
library(rvest)
library(tidyverse)
library(DT)
library(shiny)
library(htmltools)

# Define a URL da página a ser lida
page <- "https://fundamentus.com.br/fii_resultado.php"

# Lê o conteúdo HTML da página e converte a tabela encontrada em um objeto data frame
fii <- read_html(page) %>% 
  html_table()

# Seleciona apenas a primeira tabela encontrada (que contém as informações de interesse)
# e seleciona apenas algumas colunas específicas
fii <- fii[[1]] %>% 
  select(
    Papel, Segmento, Cotação, 'Dividend Yield', 'P/VP',
    'Valor de Mercado', Liquidez, 'Vacância Média'
  ) %>% 
  
  # Faz a limpeza dos dados das colunas Cotação a Vacância Média
  # Substitui o caractere "." e "%" por vazio, transforma "," em "." e converte o tipo para numérico
  mutate(
    across(Cotação:'Vacância Média', gsub, pattern = "\\.|%", replacement = ""),
    across(Cotação:'Vacância Média', gsub, pattern = ",", replacement = "."),
    across(Cotação:'Vacância Média', as.numeric),
  )  %>%
  
  # Formata as colunas "Valor de Mercado" e "Liquidez" como valores monetários (R$)
  mutate(
    `Valor de Mercado` = paste0("R$", format(round(`Valor de Mercado`, 2), nsmall = 2, big.mark = ".") ),
    Liquidez = paste0("R$", format(round(Liquidez, 2), nsmall = 2, big.mark = "."))
  )
 
  
  
  

```

Column {.sidebar}
-----------------------------------------------------

```{r echo=FALSE}
numericInput(
  "cotacao", label = "VALOR DA COTA ATÉ:",
  value = 150
)

numericInput(
  "dividend_yeld", label = "DIVIDEND YIELD MAIOR QUE:",
  value = 4
)

sliderInput(
  "p_vp", label = "P/PV entre:",
  min = 0, max = 2.5, step = 0.1,
  value = c(0.3, 1.5)
)

sliderInput(
  "valor_mercado", label = "VALOR DE MERCADO MAIOR QUE",
  min = 0, max = 2000000000, step = 500000000,
  value = 500000000, pre = "R$"
)

sliderInput(
  "liquidez", label = "LIQUIDEZ MAIOR QUE",
  min = 0, max = 2000000, step = 500000,
  value = 1000000, pre = "R$"
)

sliderInput(
  "vacancia", label = "VACÂNCIA MÉDIA MENOR QUE:",
  min = 0, max = 30, step = 5,
  value = 30, post = "%"
)


```

Column
--------------------------------------------------------
### Fundos Imobiliários

```{r echo=FALSE, message=TRUE, warning=TRUE, paged.print=TRUE}
 renderDataTable({
   fii %>%
     filter(
        Cotação <= input$cotacao,
        'Dividend Yield' >= input$dividend_yeld,
       # 'P/VP' >= input$p_vp[1], 'P/VP' <= input$p_vp[2],
       'Valor de Mercado' >= input$valor_mercado,
        Liquidez >= input$liquidez,
       #'Vacância Média' <= input$vacancia
     ) %>%
     datatable(rownames = FALSE) %>%
     formatRound(c('Dividend Yield', 'Vacância Média', 'Cotação', 'P/VP'), digits = 2)
 })
```


```{r echo=FALSE}
# renderUI({
#   if (is.null(input$p_pv[1])) {
#     div(
#       h4("Aviso:"),
#       p("O filtro de P/VP não foi aplicado porque não há um valor válido definido.")
#     )
#   } else {
#     renderDataTable({
#       fii %>% 
#         filter(
#           Cotação <= input$cotacao,
#           'Dividend Yield' >= input$dividend_yeld,
#           'P/VP' >= input$p_pv[1], `P/VP` <= input$p_pv[2],
#           'Valor de Mercado' >= input$valor_mercado,
#           Liquidez >= input$liquidez,
#           'Vacância Média' <= input$vacancia
#         ) %>% 
#         datatable(rownames = FALSE) %>% 
#         formatRound(c('Dividend Yield', 'Vacância Média', 'Cotação', 'P/VP'), digits = 2)
#     })
#   }
# })
```

